In [60]:
"""Задание 1
Создайте numpy array с элементами от числа N до 0 
(например, для N = 10 это будет array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0]))."""

import numpy as np

#указываем левую границу минус 1, правую границу -1 и шаг -1, т.к. хотим получить массив в обратном порядке
a = np.arange(9,-1,-1)
a

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [31]:
"""Задание 2
Создайте диагональную матрицу с элементами от N до 0. Посчитайте сумму ее значений на диагонали."""

#создаем диагональную матрицу
b = np.diag(a)
b

array([[9, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 8, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 7, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 6, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 3, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 2, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [33]:
#создаем вектор,состоящий из диагональных элементов
diag = np.diagonal(b)
diag

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [35]:
#считаем сумму элементов
res = diag.sum()
res

45

In [51]:
"""Задание 3
Решите систему уравнений:
4x + 2y + z = 4
x + 3y = 12
5y + 4z = -3
"""

#коэффициенты при переменных в левой части уравнения
a = np.array([ [4, 2, 1], 
     [1, 3, 0],
     [0, 5, 4] ])

In [52]:
#значения в правой части уравнения
b =  np.array([4, 12, -3] )

In [53]:
#решение

from numpy import linalg

In [55]:
linalg.solve(a, b)

array([ 0.46666667,  3.84444444, -5.55555556])

In [56]:
#проверка 
np.allclose( np.dot(a, linalg.solve(a, b)), b )

True

In [ ]:
"""Задание 4
Имеется матрица покупок в интернет-магазине. Столбец А - ID пользователя. 
Остальные столбцы - количество покупок категорий товаров этим пользователем:"""

In [62]:
#матрица в виде numpy array

users_stats = np.array(
    [
        [2, 1, 0, 0, 0, 0],
        [1, 1, 2, 1, 0, 0],
        [2, 0, 1, 0, 0, 0],
        [1, 1, 2, 1, 0, 1],
        [0, 0, 1, 2, 0, 0],
        [0, 0, 0, 0, 0, 5],
        [1, 0, 0, 0, 0, 0],
        [0, 1, 1, 0, 0, 0],
        [0, 0, 0, 1, 1, 3],
        [1, 0, 0, 2, 1, 4]
    ], 
    np.int32
)


In [63]:
#на сайт заходит очередной посетитель, о покупках которого известно следующее:

next_user_stats = np.array([0, 1, 2, 0, 0, 0])

In [71]:
"""найдите самого похожего пользователя.
т. е. посчитайте косинусное сходство между этим пользователем и всеми пользователями из массива  user_stats"""

def cosine( users_stats, next_user_stats ):
    """
    Подсчет косинуса угла между векторами users_stats и next_user_stats по их координатам
    """
    # длины векторов
    users_stats_len = np.linalg.norm( users_stats )
    next_user_stats_len = np.linalg.norm( next_user_stats )
    
    return np.dot( users_stats, next_user_stats ) / ( users_stats_len * next_user_stats_len )


In [76]:
"""применяем функцию cosine к каждой строке. аргумент 1 указывает,что ф-ия должна вызываться для строк"""

cos_ = np.apply_along_axis(cosine, 1, users_stats, next_user_stats)
cos_

array([0.2       , 0.84515425, 0.4       , 0.79056942, 0.4       ,
       0.        , 0.        , 0.9486833 , 0.        , 0.        ])

In [77]:
"""Функция np.argmax находит индекс элемента, который соответствует максимальному 
значению массива. Чем косниус ближе к 1, тем меньше угол и значит больше схожесть"""
best_user = np.argmax(cos_)
best_user

7